sudo: required
language: python
services:
  - docker
# before_install:
#   - docker pull mongo
#   - docker run -d -p 127.0.0.1:27017:27017 mongo
#   - doc
before_script:
  - npm install -g gulp
python:
  - "3.6"
node_js:
  - "node"
install:
    - pip install coveralls
script: "./uranium test"
after_success:
    coveralls
