sudo: required
language: python
services:
  - docker
before_script:
  - npm install -g gulp
python:
  - "3.6"
node_js:
  - "node"
install:
    - pip install coveralls
script: "./uranium test"
after_success:
    coveralls