sudo: required
language: python
services:
  - docker
before_install:
  - docker pull mongo
  - docker run -d -p 127.0.0.1:27017:27017 mongo
  - docker ps -a
python:
  - "3.6"
install:
    - pip install coveralls
script: "./uranium test"
after_success:
    coveralls
